name: Test Workflow

on:
  workflow_dispatch:
    inputs:
      username:
        type: string
        required: true

jobs:
  call-workflow-passing-data:
    uses: jwatkins12/reuse-test/.github/workflows/reuse.yml@main
    with:
      username: ${{ github.event.inputs.username }}
    secrets:
      token: ${{ secrets.TOKEN }}